### ISSUE TITLE
Does rppal support non-blocking SPI?

### ISSUE THREAD

**Issue by imrank03** [golemparts/rppal#118]
Hi, Does SPI support non-blocking mode, if supported how to do it?

**Comment by golemparts** [comment]
Hi @imrank03. SPI doesn't support non-blocking mode at this time, because it's limited by the features provided by the underlying linux driver.

If non-blocking/async SPI is a requirement for your project, you could theoretically use the current synchronous implementation, run an instance of `Spi` on a separate thread, and communicate with it through channels to buffer writes, reads and transfers.

**Comment by imrank03** [comment]
Hello @golemparts, thanks for the clarification.
