### ISSUE TITLE
Read Output pin level

### ISSUE THREAD

**Issue by rahul-thakoor** [golemparts/rppal#18]
Hey there. Is there a way to read the current level of an OutputPin?
My use case if being able to tell if pin is active or not. For now, I am saving state everytime I change the pin level.

**Comment by golemparts** [comment]
I actually had some read methods as part of `OutputPin` during development, but decided against keeping them in, because the user should already be aware of the level they set the pin at, and they can keep track of it just like you're doing now. You can still read the initial state of the pin by using the `read` method on the `Pin` instance you get back from `Gpio::get`, before converting it to an `OutputPin`. 

If I were to re-add those read methods, checking the relevant registers would add additional overhead, so saving state would still be a faster way of keeping track. I don't mind adding them back in with the next release if there's enough demand for it though.

Are you trying to accomplish anything in particular where you need to know the state of the `OutputPin`, or do you just want to be able to return it as a convenience to the users of your library?

**Comment by golemparts** [comment]
Actually, now that I think about it, reading the pin's level before configuring it would only make sense if it was already previously configured for output, so that might not be that useful to you.

**Comment by rahul-thakoor** [comment]
Yes am trying to replicate behaviour in gpiozero library. I am trying to implement active high/low. So I need to be able to read the value of the pin to interprete  whether the pin is active or not.


________________________________

**Comment by golemparts** [comment]
When I removed the methods, I assumed there would be no use case for them, but it sounds nice to have in your situation, so I'll add them to the list for the 0.11.0 release!

You'll have to save state internally for now, or alternatively, you might be able to work with `IoPin` instead, which does allow you to call `read`, `is_low` and `is_high` on a pin set for output.

**Comment by rahul-thakoor** [comment]
Great!! Thanks for the tip. Also great work on this crate. I have learnt so much from it.


________________________________

**Comment by golemparts** [comment]
Thanks for the compliment! It's always great to hear my code has been useful to other people as well.

Speaking of which, I'll likely push my initial implementation of software-based PWM to the master branch later this week, so you'll have something new to go through. I still have a few more things to try first before I'm ready to settle for 'good enough' :smile:.
